- hosts: foreign
  tasks:
  - name: gather facts
    ansible.builtin.service_facts:
    
  - name: stop foreign backend
    become: yes
    become_user: root
    become_method: sudo
    systemd:
      name: apache2
      state: stopped
      enabled: no
    when: ansible_facts.services['apache2.service'] is defined and ansible_facts.services['apache2.service'].state == 'running'

- hosts: local
  tasks:
  - name: gather facts
    ansible.builtin.service_facts:
    
  - name: start local backend
    become: yes
    become_user: root
    become_method: sudo
    systemd:
      name: apache2
      state: started
      enabled: yes
    when: ansible_facts.services['apache2.service'] is defined and ansible_facts.services['apache2.service'].state != 'running'
